services:
  signaling-server:
    build:
      context: ./src/signaling-server
      dockerfile: Dockerfile
    container_name: signaling_server
    networks:
      - abr_net
    restart: always

  cloud-node:
    build:
      context: ./src/cloud-node
      dockerfile: Dockerfile
    container_name: cloud_node_container
    cap_add:
      - NET_ADMIN
    volumes:
      - ./src/shared:/app/shared
    networks:
      - abr_net
    depends_on:
      - signaling-server
    restart: always

  edge-node:
    build:
      context: ./src/edge-node
      dockerfile: Dockerfile
    container_name: edge_node_container
    volumes:
      - ./src/shared:/app/shared        # HW status + webrtc stats
      - ./src/video:/app/video          # video files to stream
      - ./src/model:/app/model          # persisted .npz weights
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    networks:
      - abr_net
    depends_on:
      - cloud-node
      - signaling-server
    restart: always

networks:
  abr_net:
    driver: bridge