services:
  # cloud-node:
  #   build:
  #     context: ./src/cloud-node
  #     dockerfile: Dockerfile
  #   container_name: cloud_node_container
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     - abr_net
  #   restart: always

  edge-node:
    build:
      context: ./src/edge-node
      dockerfile: Dockerfile
    container_name: edge_node_container
    volumes:
      - ./src/shared:/app/shared
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 32M
    # networks:
    #   - abr_net
    # depends_on:
    #   - cloud-node
    restart: always

networks:
  abr_net:
    driver: bridge